exports.courts = [
  { court: 'Syd Kronenthal Park', location: '3459 McManus Ave., Culver City, CA 90232' },
  { court: 'Montecito Heights Recreation Center', location: '4545 Homer St, Los Angeles, CA 90031' },
  { court: 'Granada Hills Recreation Center (Petit Park)', location: '16730 Chatsworth St, Granada Hills, CA 91344' },
  { court: 'Encino Recreation Center', location: '16953 Ventura Blvd, Encino, CA 91316' },
  { court: 'Chatsworth Recreation Center', location: '22360 Devonshire St., Chatsworth, CA 91311' },
  { court: 'Balboa Sports Complex/Tennis', location: '17015 Burbank Blvd, Encino, CA 91316' },
  { court: 'Manhattan Heights', location: 'North Herrin Avenue & Manhattan Beach, Manhattan Beach, CA 90266' },
  { court: 'iTennis Arcadia', location: '405 S Santa Anita Ave, Arcadia, CA 91006' },
  { court: 'Hermosa Beach Tennis Courts', location: '560 11th St, Hermosa Beach, CA 90254 and more across the street.' },
  { court: 'El Segundo Parks & Recreation', location: '401 Sheldon St, El Segundo, CA 90245' },
  { court: 'Darby Park', location: '3400 W Arbor Vitae St, Inglewood, CA 90305' },
  { court: 'Allendale Park', location: '1130 S Marengo Ave, Pasadena, CA 91106' },
  { court: 'Larry L. Maxam Park', location: '3800 Valhalla Dr, Burbank, CA 91505' },
];